from __future__ import annotations

import logging
import re
from typing import Any, Dict, Optional

from groq import AsyncGroq

from brain.config import GROQ_API_KEY, GROQ_MODEL, has_groq_api_key

logger = logging.getLogger("groq_voice")

FRIDAY_SYSTEM_PROMPT = """You are Friday, an ultra-fast, intelligent, and highly capable personal AI assistant (inspired by Iron Man's FRIDAY / JARVIS).
Your communication style:
- Charismatic, polite, warm, concise, and slightly witty when appropriate.
- Refer to the user respectfully as 'sir'.
- Keep responses short and impactful (1 to 2 sentences max).
- Confidently inform the user of actions completed by the system (e.g. reminders set, tasks created, meetings cancelled, schedule briefings).
- If the user is disappointed (e.g. client ditched), be empathetic and encouraging.
- Do NOT output internal thoughts, reasoning tags, or metadata—only the spoken response.
"""


def _clean_model_output(text: str) -> str:
    """Removes any <think> tags or reasoning blocks if generated by reasoning models."""
    if not text:
        return ""
    cleaned = re.sub(r"<think>.*?</think>", "", text, flags=re.DOTALL).strip()
    return cleaned


async def generate_friday_reply(
    user_input: str,
    action_summary: str,
    context: Optional[Dict[str, Any]] = None,
) -> str:
    """
    Generates a natural, conversational Friday response based on the completed action.
    """
    if not has_groq_api_key():
        logger.info("GROQ_API_KEY not found in environment; using template fallback.")
        return _fallback_reply(user_input, action_summary)

    try:
        groq_client = AsyncGroq(api_key=GROQ_API_KEY)
        messages = [
            {"role": "system", "content": FRIDAY_SYSTEM_PROMPT},
            {
                "role": "user",
                "content": (
                    f"User Message: '{user_input}'\n"
                    f"Action Completed by System: {action_summary}\n"
                    f"Context Details: {context or {}}\n\n"
                    "Respond to the user naturally and concisely as Friday."
                ),
            },
        ]

        response = await groq_client.chat.completions.create(
            model=GROQ_MODEL,
            messages=messages,
            temperature=0.7,
            max_tokens=350,
        )

        message = response.choices[0].message
        raw_content = message.content or ""
        reply = _clean_model_output(raw_content)

        if not reply:
            logger.warning("Groq model returned empty message content, falling back to template reply.")
            return _fallback_reply(user_input, action_summary)

        logger.info(f"🗣️ [Friday Voice/Groq] Generated reply: '{reply}'")
        return reply

    except Exception as exc:
        logger.error(f"Error calling Groq API ({GROQ_MODEL}): {exc}. Using fallback response.", exc_info=True)
        return _fallback_reply(user_input, action_summary)


def _fallback_reply(user_input: str, action_summary: str) -> str:
    """Natural fallback templates if API key is missing or model fails."""
    lower = user_input.lower()
    if any(k in lower for k in ("on my plate", "daily briefing", "my schedule", "agenda", "what do i have", "whats on my")):
        return f"Here is your agenda overview, sir: {action_summary}"
    elif any(k in lower for k in ("ditched", "cancel", "cancelled", "clear")):
        return "Oh, sorry to hear that sir! But no worries, we'll get another one. I have cleared the meeting from your schedule."
    elif any(k in lower for k in ("meeting", "remind", "reminder")):
        return f"Understood, sir. I have scheduled that reminder for you and will notify your device ahead of time."
    elif any(k in lower for k in ("task", "todo", "add")):
        return "Done, sir. I've added that task to your work list."
    else:
        return f"Right away, sir. {action_summary}"
